name: Bug Issue Template
description: File a Bug Issue Report
title: "[Bug]: "
labels: [
  "hacktoberfest",
  "hacktoberfest-accepted"
]
body:
  - type: input
    id: bug-title
    attributes: 
      label: Bug Title
      placeholder: ex. [BUG] title
    validations: 
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description of BUG
      placeholder: Description of the BUG
    validations:
      required: true
  - type: input 
    id: url
    attributes:
      label: Reporduction URL of bug 
      placeholder: URL where we can find the bug
    validations:
      required: false
  - type: dropdown
    id: issue-type
    attributes:
      label: Bug Issue Type
      description: Which type of bug issue?
      options:
        - Frontend
        - Backend
        - Documentation
    validations:
      required: true
  - type: textarea
    id: screenshot
    attributes:
      label: Screenshot of the issue if in UI/ Document
    validations:
      required: false
  - type: input
    id: taking-issue
    attributes:
      label: Are you taking this issue fix
      placeholder: Yes/ No
    validations:
      required: true